### ISSUE TITLE
Potential parallel bug with solute transport in v1.5.1?

### ISSUE THREAD

**Issue by smolins** [amanzi/ats#285]
I identified two issues with solute transport in ATS v1.5.1. These issues have been affecting reactive transport but I was able to narrow down to potential issues with transport. I cannot reproduce these issues in a 1D test simulation but it is still unclear to me why these appear only in higher dimensionality simulations. Also, it is unclear whether they are related or not. 

The file attached is a transport version of the demo under ats-demos/13_integrated_hydro_reactive_transport/hillslope_calcite_crunch_sigmoid.xml, which is described in Molins et al 2022 WRR. Here it is modified to include only 1 tracer, with initial concentration in the domain = 1 and =0 in the rain water ( hillslope_transport_sigmoid_100s.xml) 

[hillslope_transport_sigmoid_100s.txt](https://github.com/user-attachments/files/18143452/hillslope_transport_sigmoid_100s.txt)

The 2 issues are

1. parallel simulations result in concentration hotspots that repeat as many times as the number processors one is using. The plot for time = 1 day is presented for a 4 processor run. (parallel.png)

![parallel](https://github.com/user-attachments/assets/af12d5cf-042a-480e-b94a-128139187f46)

2. as the water table drops in the uphill portion of the domain from the initial position due to drainage in the bottom, the concentrations of the tracer increase above 1. That cannot be. At the same time concentrations of the tracer in the downhill portion of the domain decrease below zero, as that area's liquid saturation increases so that the initial water can exit through the surface . This is apparent as early as time = 3 days (concentration.png , note: this was obtained in a serial run to avoid mixing in the parallel issues) but gets worse as time advances. 

![concentration](https://github.com/user-attachments/assets/e034e1c6-59f7-4fc7-86f4-b11b5de19167)

There is another issue with concentrations that appears at time = 1 day near the left boundary. This issue is buried by issue 2 at time = 3 days. The position of the cell with an off concentration is suspiciously close to the position of the "hot" cells in the parallel runs.

**Comment by smolins** [comment]
I am adding a figure for the last point I raise above. It seems related to the issue raised in point 1 but parallel runs may make it more apparent. 

![concentration1day](https://github.com/user-attachments/assets/f274cdd2-432a-4cac-b0fa-bf1bf9710c86)

**Comment by dasvyat** [comment]
One of the source of this bug is subcyling. With simple week coupling there is no overshoots (at least on 1 core). I'm looking into this issue

**Comment by smolins** [comment]
I looked a little more into this issue and have not been able to link it clearly to anything. However, I do see that the initial velocities show the same striped pattern from some sort of parallel issue. This pattern disappears right away with the Darcy velocities but then little by little appears in the concentrations. 

![velocity_time_zero](https://github.com/user-attachments/assets/ebbfec65-bd23-4be7-a9ff-34caf5730a1f)

Could any of you @levuvietphong or @dasvyat comment whether there could an issue that connected the initial velocities with the concentration hotspots showing up in the early transport. 

This issue is not a big deal for transport as these differences are small and they are soon overwhelmed by larger concentration differences (like when a front arrives) but when coupled to geochemistry, this leads to problems. For example, it may change mineral or sorbed concentrations which remain like that for the rest of the simulation.

**Comment by dasvyat** [comment]
@smolins , I looked into this issues and for my surprise, it is not a transport issue, in my opinion. The discrepancies are coming directly from flow.  I don't know what is the reason at the moment. I've increased nonlinear tolerance with the hope that it can help, but it didn't. I'm looking into this issue.

**Comment by ecoon** [comment]
Is it in velocities or in fluxes?  I would be very surprised if it was in fluxes, but less surprised if it was in velocities/reconstruction, since we rarely look at those.  I know that most of transport uses fluxes, but are you using a velocity-dependent dispersion?

**Comment by smolins** [comment]
These simulations do no include dispersion (i.e. dispersion not in the input file) and diffusion uses default values (0.0, I assume).

**Comment by ecoon** [comment]
Ok, then I'm not sure if transport uses velocity anywhere else.

I'm not sure of the magnitudes here -- is it possible that this is due to block preconditioners?  Does this go away if you use e.g. Boomer AMG?

**Comment by dasvyat** [comment]
It surprised me a lot that the difference in flux (or flux_dir or uw_k_rel). I don't understand is it new or old problem. It may happen at the first iteration. These the results after 1 iteration and run with the same input file on 1 and 4 cores. Nonlinear tolerance is 1e-12, so I don't think that different precondtioners will play any role.
******
1 CORE:

flow               |  p_old      (  240):   125850.0000000  101325.0000000  125850.0000000  150375.0000000  125850.0000000  125850.0000000  125850.0000000
flow               |  p_new      (  240):   125850.0000000  101325.0000000  125850.0000000  150375.0000000  125850.0000000  125850.0000000  125850.0000000
flow               |     Updating BCs.
flow               |     BCs applied:
flow               |       pressure: 0
flow               |       head: 0
flow               |       head: 0
flow               |       water_flux: 0
flow               |       standard seepage: 0
flow               |       seepage with infiltration: 0
flow               |       surface coupling (head): 0
flow               |       surface coupling (flux): 120
flow               |       default (zero flux): 1572
flow               |  BCs        (  240): 0(     0.      )0(     0.      )0(     0.      )2(     0.      )2(     0.      )2(     0.      )
flow               |     Updating permeability? 1
flow               |  sl_old     (  240):        1.0000000       1.0000000       1.0000000       1.0000000
flow               |  sl_new     (  240):        1.0000000       1.0000000       1.0000000       1.0000000
flow               |  poro       (  240):        0.2500000
flow               |  perm_K     (  240):    5.0000000e-11
flow               |  k_rel      (  240):        6.2359551       6.2359551       6.2359551       6.2359551
flow               |  wind       (  240):   -1.4210855e-14  -7.1054274e-15  -7.1054274e-15   5.6843419e-14   1.3642421e-12   1.3642421e-12
flow               |  uw_k_rel   (  240):        3.1179779       6.2359551       6.2359551       6.2359551       6.2359551       6.2359551
flow               |  flux       (  240):   -4.2632564e-14   5.6843419e-14   2.8421709e-14   2.2737368e-13   1.0913936e-11   1.0913936e-11
flow               |  res (diff) (  240):    1.9795721e-11  -5.6843419e-14  -3.4106051e-13  -6.8212103e-13  -2.2737368e-13  -1.0913936e-11  -1.0913936e-11
flow               |  res (acc)  (  240):    1.9795721e-11  -5.6843419e-14  -3.4106051e-13  -6.8212103e-13  -2.2737368e-13  -1.0913936e-11  -1.0913936e-11

*******
4 CORE:

flow               |  p_old      (  240):   125850.0000000  101325.0000000  125850.0000000  150375.0000000       0.         125850.0000000  125850.0000000
flow               |  p_new      (  240):   125850.0000000  101325.0000000  125850.0000000  150375.0000000       0.         125850.0000000  125850.0000000
flow               |  BCs        (  240): 0(     0.      )0(     0.      )0(     0.      )0(     0.      )2(     0.      )2(     0.      )
flow               |     BCs applied:
flow               |       pressure: 0
flow               |       head: 0
flow               |       head: 0
flow               |       water_flux: 0
flow               |       standard seepage: 0
flow               |       seepage with infiltration: 0
flow               |       surface coupling (head): 0
flow               |       surface coupling (flux): 120
flow               |       default (zero flux): 1572
flow               |     Updating permeability? 1
flow               |  flux       (  240):        0.4719193      -7.8653210       0.4719193      -7.8653210  -3.6379788e-12  -3.6379788e-12
flow               |  sl_old     (  240):        1.0000000       1.0000000       1.0000000
flow               |  sl_new     (  240):        1.0000000       1.0000000       1.0000000
flow               |  poro       (  240):        0.2500000
flow               |  perm_K     (  240):    5.0000000e-11
flow               |  k_rel      (  240):        6.2359551       6.2359551       6.2359551
flow               |  wind       (  240):        0.0756771      -1.2612857       0.0756771      -1.2612857  -4.5474735e-13  -9.0949470e-13
flow               |  uw_k_rel   (  240):        6.2359551       6.2359551       6.2359551       6.2359551       6.2359551       6.2359551
flow               |  flux       (  240):        0.4719193      -7.8653210       0.4719193      -7.8653210  -3.6379788e-12  -3.6379788e-12
flow               |  res (diff) (  240):        0.         -1.1368684e-13   1.1368684e-13       0.              7.8653210   3.6379788e-12   3.6379788e-12
flow               |  res (acc)  (  240):        0.         -1.1368684e-13   1.1368684e-13       0.              7.8653210   3.6379788e-12   3.6379788e-12



I don't understand why fluxes and wind are that much different. This is output after just one iteration of nonlinear solver. Due to these differences it results  in different solution.

**Comment by dasvyat** [comment]
I forgot to mention this is flow only simulation

**Comment by dasvyat** [comment]
I withdraw my previous comment. My comparison was wrong

**Comment by levuvietphong** [comment]
Danil's PR (#290) has fixed the stripe pattern in the velocity.2 field at t=0. However, I ran the `hillslope_calcite_crunch_sigmoid.xml` example again and I got the problem of no convergence at a specific cell (see log below). Do you have the same issue?


![Image](https://github.com/user-attachments/assets/eb84c7b0-557b-4951-bb15-2d6ede70c900)

```
Alquimia_PK:domain |  no convergence in cell: 1427
reactive transport |  Alquimia_PK:domain failed.
surface transport  |  ----------------------------------------------------------------
surface transport  |  Advancing: t0 = 252751 t1 = 252841 h = 89.5266
surface transport  |  ----------------------------------------------------------------
surface transport  |  1 sub-cycles, dt_stable=1.49211 min [sec]  dt_MPC=1.49211 min [sec]
subsurface transpo |  ----------------------------------------------------------------
subsurface transpo |  Advancing: t0 = 252751 t1 = 252841 h = 89.5266
subsurface transpo |  ----------------------------------------------------------------
inverse::PCG       |  Converged (relative RHS), itr=1 ||r||=5.6449e-19 ||f||=90.9331
inverse::PCG       |  Converged (relative RHS), itr=1 ||r||=2.09579e-14 ||f||=27949.6
inverse::PCG       |  Converged (relative RHS), itr=1 ||r||=1.16336e-14 ||f||=829934
inverse::PCG       |  Converged (relative RHS), itr=1 ||r||=9.95036e-15 ||f||=1.05614e+07
inverse::PCG       |  Converged (relative RHS), itr=1 ||r||=9.80417e-22 ||f||=1.05614
subsurface transpo |   dispersion solver ||r||=8.50849e-15 itrs=1
subsurface transpo |  1 sub-cycles, dt_stable=7.29735 min [sec]  dt_MPC=1.49211 min [sec]
Alquimia_PK:surfac |  min/avg/max Newton: 0/0/1, the maximum is in cell 98
No convergence at:            1           1           1
```

**Comment by smolins** [comment]
Did you try to run the transport-only version of the problem?

https://github.com/user-attachments/files/18143452/hillslope_transport_sigmoid_100s.txt

**Comment by smolins** [comment]
You would need to modify any of these files such that time step size is
capped to 70 seconds, not 100 seconds

**Comment by levuvietphong** [comment]
I ran again the [hillslope_transport_sigmoid_100s.txt](https://github.com/user-attachments/files/18143452/hillslope_transport_sigmoid_100s.txt) example:
- **The vertical stripes are still present**. Probably, I made a mistake that I visualize results from a serial run instead of a parallel run in my previous post.
- The stripes are in both `darcy_velocity.0` and `darcy_velocity.2` fields
- The number of vertical stripes correspond to `N-1`, where `N` is the number of processors used in the parallel run. So I guess @smolins used 8 processors in the plot he showed, leading to 7 vertical stripes. It looks like to me the stripes are at the `halo zone` of each subdomain.
- The stripes go away immediately in the next time step. May be it a parallel problem in the initialization step only.

**Comment by dasvyat** [comment]
To investigate parallel issue I suggest to switch to weak coupling instead of subcycling to simplify the model. Moreover, something happened between 1.5.1 and current master. When I've added parallel communication to 1.5.1 there were no stripes. After I've merged it with master they have appeared. @levuvietphong can you confirm that using amanzi-1.5.1 and dsv/test_ats-1.5.1 you don't see stripes either.

[hillslope_transport_sigmoid_100s_weak.txt](https://github.com/user-attachments/files/18526798/hillslope_transport_sigmoid_100s_weak.txt)

**Comment by levuvietphong** [comment]
@dasvyat: No, using amanzi-1.5.1 and dsv/test_ats-1.5.1 I still see the stripes. This run used 4 cores.

<img width="1335" alt="Image" src="https://github.com/user-attachments/assets/102e2838-4950-4640-9817-6fccc5cac6b8" />

**Comment by dasvyat** [comment]
What are you plotting? And what is  the range?

**Comment by levuvietphong** [comment]
@dasvyat: I updated the plot. It is the `darcy_velocity.2`

**Comment by dasvyat** [comment]
@levuvietphong What is about tracer concentration? Darcy velocity is not the best indicator. It is a post-processed quantity which is computed based on face unknown for visualization. After how many days do you plot it?

**Comment by dasvyat** [comment]
Currently, darcy velocity is computed at the initialization stage without parallel update. That's why stripes are observed at t=0. It can be (should be) corrected, but it is not a big deal since during actual AdvanceStep this parallel update is performed and concentration ( and all other fields are updated correctly). The pattern in concentration should not be observed.

**Comment by levuvietphong** [comment]
The tracer concentration is consistently 1.0 across the domain and over time. Below is the `total_component_quantity.tracer` field. 

![Image](https://github.com/user-attachments/assets/04a5338b-d658-41e2-9eab-4d45ac7b2382)
